name: Sort YAML on Push

# Trigger the workflow on push to the master branch
on:
  push:
    branches:
      - master

jobs:
  sort_yaml:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the latest version of the repo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Provide write permissions so the action can push changes
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # Step 3: Install PyYAML (to handle YAML files)
      - name: Install PyYAML
        run: |
          pip install pyyaml

      # Step 4: Run the Python sorting script
      - name: Sort YAML file
        run: |
          python sort_yaml.py

      # Step 5: Check if the file has changed (do not exit on changes)
      - name: Check for changes
        run: |
          git diff --exit-code dns_to_ip.yaml || echo "Changes detected, proceeding to commit."

      # Step 6: Commit and push sorted file if changes occurred
      - name: Commit and push sorted file
        if: always() # Always run this step
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name 'GitHub Actions'
            git config --global user.email 'actions@github.com'
            git add dns_to_ip.yaml
            git commit -m "Auto-sorted YAML file"
            git push;
          else
            echo "No changes to commit.";
          fi
